# Generated by Django 4.2 on 2023-05-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='nom du repas', max_length=70)),
                ('calorie', models.IntegerField(help_text='nobre de calorie')),
                ('type_Aliment', models.CharField(choices=[(1, 'Fruit'), (2, 'Legume'), (3, 'Viande'), (4, 'Poisson'), (5, 'autre')], default=5, help_text="le type d'aliment consommes", max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jour', models.CharField(choices=[(1, 'lundi'), (2, 'mardi'), (3, 'mercredi'), (4, 'jeudi'), (5, 'vendredi'), (6, 'samedi'), (7, 'dimanche')], default=1, help_text='identifiant du jour', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='votre nom svp', max_length=200)),
                ('password', models.CharField(help_text='votre mot de passe', max_length=70)),
                ('age', models.PositiveIntegerField(help_text='votre age ici')),
                ('sexe', models.CharField(help_text='votre sexe', max_length=10)),
                ('taille', models.IntegerField(help_text='votre taille svp en cm (exemple:145)')),
                ('poids', models.IntegerField(help_text='votre poids actuel')),
            ],
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='nom du probleme de sante', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='nom du symptomes', max_length=70)),
                ('gravite', models.CharField(choices=[(1, 'null'), (2, 'faibles'), (3, 'moyen'), (4, 'graves'), (5, 'tres graves')], default=1, help_text='niveau de gravite de 1 a 5', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Consomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(help_text='preciser la quantite en entier')),
                ('id_aliments', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Foodapp.aliment')),
                ('id_jour', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Foodapp.jour')),
                ('id_probleme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Foodapp.probleme')),
            ],
        ),
    ]
