# Generated by Django 4.2 on 2023-05-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='password',
        ),
        migrations.AddField(
            model_name='jour',
            name='repas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Foodapp.aliment'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='type_Aliment',
            field=models.CharField(choices=[('1', 'Fruit'), ('2', 'Legume'), ('3', 'Viande'), ('4', 'Poisson'), ('5', 'autre')], default='autres', help_text="le type d'aliment consommes", max_length=10),
        ),
        migrations.AlterField(
            model_name='jour',
            name='id_jour',
            field=models.CharField(choices=[('1', 'lundi'), ('2', 'mardi'), ('3', 'mercredi'), ('4', 'jeudi'), ('5', 'vendredi'), ('6', 'samedi'), ('7', 'dimanche')], default=1, help_text='identifiant du jour', max_length=1),
        ),
        migrations.AlterField(
            model_name='symptome',
            name='gravite',
            field=models.CharField(choices=[('1', 'null'), ('2', 'faibles'), ('3', 'moyen'), ('4', 'graves'), ('5', 'tres graves')], default=1, help_text='niveau de gravite de 1 a 5', max_length=10),
        ),
    ]
