# Generated by Django 4.2 on 2023-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0004_rename_id_p_consomation_nom_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jour',
            name='id_jour',
            field=models.CharField(choices=[('Lundi', '1'), ('Mardi', '2'), ('Mercredi', '3'), ('Jeudi', '4'), ('Vendredi', '5'), ('Samedi', '6'), ('Dimanche', '7')], default=1, help_text='identifiant du jour', max_length=11),
        ),
    ]
