# Generated by Django 4.2 on 2023-05-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0005_alter_jour_id_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='jour',
            name='Nom_Personne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Foodapp.personne'),
        ),
        migrations.AlterField(
            model_name='jour',
            name='id_jour',
            field=models.CharField(choices=[('Lundi', '1'), ('Mardi', '2'), ('Mercredi', '3'), ('Jeudi', '4'), ('Vendredi', '5'), ('Samedi', '6'), ('Dimanche', '7')], default='Lundi', help_text='identifiant du jour', max_length=11),
        ),
    ]
