# Generated by Django 4.2 on 2023-05-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0006_jour_nom_personne_alter_jour_id_jour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptome',
        ),
        migrations.AddField(
            model_name='probleme',
            name='gravite',
            field=models.CharField(choices=[('1', 'null'), ('2', 'faibles'), ('3', 'moyen'), ('4', 'graves'), ('5', 'tres graves')], default=1, help_text='niveau de gravite de 1 a 5', max_length=10),
        ),
        migrations.AddField(
            model_name='probleme',
            name='symptome',
            field=models.CharField(default=1, help_text='nom du symptomes', max_length=70),
            preserve_default=False,
        ),
    ]
