# Generated by Django 4.2 on 2023-06-04 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0007_delete_symptome_probleme_gravite_probleme_symptome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='probleme',
            field=models.ManyToManyField(blank=True, to='Foodapp.probleme'),
        ),
        migrations.CreateModel(
            name='AlimentProbleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risque', models.FloatField(default=0)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodapp.aliment')),
                ('probleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodapp.probleme')),
            ],
        ),
    ]
