# Generated by Django 4.2 on 2023-06-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0008_aliment_probleme_alimentprobleme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlimentProbleme',
        ),
    ]
